### ISSUE TITLE
Remove revisions from VehicleInterfaces.UsersGuide.Contact

### ISSUE THREAD

**Issue by tobolar** [modelica/VehicleInterfaces#15]
In order to simplify the maintenance of the library, I would suggest to delete the years range from the copyright information contained in 'Revisions' of VehicleInterfaces.UsersGuide.Contact. Or even better to delete that Revisions completely since the relevant piece of information is already given on the main page of the library, e.g. VehicleInterfaces.

Any suggestions?

**Comment by dietmarw** [comment]
Well I would suggest to have the copyright statement in one place and keep it up to date there. Other classes can simply point to, e.g., `VehicleInterfaces.UsersGuide.Contact` for example or perhaps better: `VehicleInterfaces.UsersGuide.Copyright`

**Comment by dietmarw** [comment]
See also how it was solved in the README with simply open end year.

**Comment by tobolar** [comment]
Maybe it would be more precise to write "**since** 2013: Modelica Association"?

**Comment by tobolar** [comment]
What about to have Copyright and License agreement just at the uppermost page? It could be easy to find and be always visible for the user once he loads the library. Or should we leave the uppermost page as simple as possible?

**Comment by tobolar** [comment]
Well I noticed now, there is also VehicleInterfaces.UsersGuide.License collecting that info incl. copyright. May be the best way is to use this page and to change the icon to reflect a copyright logo?

**Comment by dietmarw** [comment]
Something similar came up here: https://github.com/dietmarw/ipsl/commit/256e2bb1e4ce001773f8e68f54460ae2f6e036d7

You could adapt that. Mind I have a n improved version with a "drawn" &copy;:
```
class Copyright "Disclaimer<html>
<h4>Copyright</h4>
...
<h4>License</h4>
...
<p> See also <a href=\"modelica://VehicleInterfaces.UsersGuide.License\">VehicleInterfaces.UsersGuide.License</a></p>
</html>"

  annotation (preferredView="info", DocumentationClass=false,
        Icon(graphics={Text(
          extent={{-100,140},{100,100}},
          lineColor={0,127,0},
          textString="%name%"),
        Ellipse(extent={{-100,100},{100,-100}}, lineColor={0,127,0},
          fillColor={255,255,255},
          fillPattern=FillPattern.Solid),
        Ellipse(
          extent={{-60,60},{60,-60}},
          lineColor={0,127,72},
          fillColor={0,127,0},
          fillPattern=FillPattern.Solid),
        Ellipse(
          extent={{-40,40},{40,-40}},
          lineColor={255,255,255},
          fillColor={255,255,255},
          fillPattern=FillPattern.Solid),
        Rectangle(
          extent={{28,22},{64,-20}},
          lineColor={255,255,255},
          fillColor={255,255,255},
          fillPattern=FillPattern.Solid)}));
end Copyright;
```

**Comment by tobolar** [comment]
I've tried to resolve this on #14. Copyright is defined on the most common way within a License agreement now and linked from the uppermost page.
The concept you suggest need broadly based discussion so we can implement it later on, if this will take place. But I've at least used your icon with slight modification :-)

**Comment by dietmarw** [comment]
I agree. So I'd say this issue is resolved then.
