### ISSUE TITLE
Remove uses of __Dymola_choicesFromPackage annotation

### ISSUE THREAD

**Issue by harmanpa** [modelica/VehicleInterfaces#27]
The tool-specific annotation ``__Dymola_choicesFromPackage`` is used in the classes ``VehicleInterfaces.DriverEnvironments.DriveByWireAutomatic`` and ``VehicleInterfaces.Drivers.MinimalDriver``

**Comment by tobolar** [comment]
Just to be sure, what is the motivation of this issue? Tool-specific annotations are generally allowed in the models. Or is it obsolete Dymola annotation?

**Comment by harmanpa** [comment]
In this case it is used as part of #25 - part of a fudge to achieve enumerations before they were used. But also this is the only library I know of using this annotation, and while ``choicesAllMatching`` was standardised, ``choicesFromPackage`` wasn't, so I'd consider it kind of obsolete.
