### ISSUE TITLE
VehicleInterfaces.Drivers.MinimalDriver cannot be instantiated

### ISSUE THREAD

**Issue by dariomangoni** [modelica/VehicleInterfaces#34]
Instantiating the `VehicleInterfaces.Drivers.MinimalDriver` should be possible, right?
Instead I get:

```
[VehicleInterfaces.Drivers: 183:5-188:31]: Failed to instantiate equation 
connect(brakePosition.flange_b, driverInterface.brakePedal) annotation(Text(string = "%second", index = 1, extent = {{6, 3}, {6, 3}}));.
```

The same happens also while running one of the examples with the `VehicleInterfaces.Drivers.MinimalDriver` e.g. `VehicleInterfaces.Examples.ConventionalAutomaticVehicleExternalDriver`

The issue arises both with OpenModelica v1.13.0 version of VehicleInterfaces and the GitHub VehicleInterfaces at commit be62651

**Comment by tobolar** [comment]
Maybe the usage of `VehicleInterfaces.Mechanics.NormalisedTranslational.Interfaces.Flange` into an expandable connector `VehicleInterfaces.Interfaces.DriverInterface` could cause the problem in OpenModelica. (Perhaps handling of component declared with the prefix `flow` in the expandable connector?)
Anyway, I can't realize such a problem using Dymola.

**Comment by tobolar** [comment]
@dariomangoni Any update?

**Comment by dariomangoni** [comment]
Well, at commit c6d3469eda1add3aa8242f35b74fb88b7f66425c the situation is the same as an year ago.
OpenModelica v1.14.0-dev-26548-gc521adfdc4 ***is not*** able to simulate.
Dymola 2020 ***is*** able to simulate the model.

**Comment by sjoelund** [comment]
OpenModelica does instantiate it:
```
loadModel(VehicleInterfaces);getErrorString();
setCommandLineOptions("-d=newInst");getErrorString();
writeFile("MinimalDriver.mof", instantiateModel(VehicleInterfaces.Drivers.MinimalDriver));getErrorString();
```
https://gist.github.com/sjoelund/6a1e18c890c51aee8534733a584eea80

But it indeed fails to simulate:
```
Error: Internal error BackendDAECreate.lowerKnownVar failed for ... Flange driverInterface.brakePedal 
```

**Comment by tobolar** [comment]
@sjoelund Many thanks. Can you further localize the problem?

**Comment by sjoelund** [comment]
@perost might be available to have a look. I don't know that much about the new frontend implementation in OpenModelica (and I'm quite busy as my teaching period just started).

**Comment by perost** [comment]
> @perost might be available to have a look. I don't know that much about the new frontend implementation in OpenModelica (and I'm quite busy as my teaching period just started).

It's an expandable connector issue, the new frontend doesn't yet handle augmenting expandable connectors with regular connectors correctly. It's on my todo list.

**Comment by tobolar** [comment]
@perost Thanks.
