### ISSUE TITLE
UsersGuide.DriverInteractionBus have misleading engineSpeed and vehicleSpeed descriptions

### ISSUE THREAD

**Issue by dariomangoni** [modelica/VehicleInterfaces#86]
In the _UsersGuide.DriverInteractionBus_'s naming convention table the measurement units for engineSpeed and vehicleSpeed have ambiguous descriptions.

engineSpeed | rad/s | Engine speed in rpm
vehicleSpeed | m/s | Vehicle speed in km/h

in both _Drivers.Internal.StandardDriverInterfaceFor<Manual|Automatic>Transmission_ and _Engines.MinimalEngine_ the engine angular speed is considered as rad/s.

Anyway, I think it's worth to make things to match. And probably, to the user interface rpm is actually the preferred choice.

**Comment by tobolar** [comment]
Actually, all signals on all control busses are given in SI units. I guess there is no exception. IMO this is also a clear rule to every user.
If any other unit shall be used in a particular model, the corresponding variable must be converted first.

I will fix the documentation.
